// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTOp7pYRvCEFwzs5zWveaigz0e3OgSf6U',
    appId: '1:802997633233:web:a6953c489dc68a644645f0',
    messagingSenderId: '802997633233',
    projectId: 'flutter-myapp1-home',
    authDomain: 'flutter-myapp1-home.firebaseapp.com',
    storageBucket: 'flutter-myapp1-home.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOZQhowuV1LFzFPEClIEwLSVrnV1AF_Ak',
    appId: '1:802997633233:android:65deb371ca4d98114645f0',
    messagingSenderId: '802997633233',
    projectId: 'flutter-myapp1-home',
    storageBucket: 'flutter-myapp1-home.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsT9m3Yvq8GZBD0Gj4oWkOn-6J2WNPk8s',
    appId: '1:802997633233:ios:0cb25e6932f599044645f0',
    messagingSenderId: '802997633233',
    projectId: 'flutter-myapp1-home',
    storageBucket: 'flutter-myapp1-home.appspot.com',
    iosBundleId: 'com.example.flutterMyapp1Home',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsT9m3Yvq8GZBD0Gj4oWkOn-6J2WNPk8s',
    appId: '1:802997633233:ios:33b64b552e6f6f824645f0',
    messagingSenderId: '802997633233',
    projectId: 'flutter-myapp1-home',
    storageBucket: 'flutter-myapp1-home.appspot.com',
    iosBundleId: 'com.example.flutterMyapp1Home.RunnerTests',
  );
}
